NCR-14625 add Apply
deliveryhero/pipeline pull request #8
Opened 2024-01-22 15:01 UTC by solokirrik

2024-01-23 14:00 UTC, marksalpeter requested changes
This looks like a useful addition to the lib and I appreciate the test coverage. This needs a `make readme` to update the readme file.

2024-01-23 15:57 UTC, marksalpeter commented on CODEOWNERS
> +* @deliveryhero/adtech-tracking-billing-sdk
maybe dh_adtech_tracking@deliveryhero.com is a good email to use?

2024-01-23 15:59 UTC, marksalpeter commented on merge_example_test.go
> +func TestExampleMerge(t *testing.T) {
heres some context to learn more about why examples are in test files: https://go.dev/blog/examples

2024-01-23 16:35 UTC, solokirrik commented on CODEOWNERS
> +* @deliveryhero/adtech-tracking-billing-sdk
Does not work. It should be a user. 
Reverted

2024-01-24 11:03 UTC, marksalpeter approved these changes
Looks good. Nice feature 👍

2024-01-24 11:05 UTC, marksalpeter commented
Can you add an example for the new `Apply` function in the readme/godoc?

2024-01-24 11:53 UTC, merged